//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWCF.Client.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.ICalculators")]
    public interface ICalculators {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculators/Add", ReplyAction="http://tempuri.org/ICalculators/AddResponse")]
        string Add(double numberA, double numberB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculators/Subtract", ReplyAction="http://tempuri.org/ICalculators/SubtractResponse")]
        string Subtract(double numberA, double numberB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculators/Multiply", ReplyAction="http://tempuri.org/ICalculators/MultiplyResponse")]
        string Multiply(double numberA, double numberB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculators/Divide", ReplyAction="http://tempuri.org/ICalculators/DivideResponse")]
        string Divide(double numberA, double numberB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorsChannel : SimpleWCF.Client.CalculatorService.ICalculators, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorsClient : System.ServiceModel.ClientBase<SimpleWCF.Client.CalculatorService.ICalculators>, SimpleWCF.Client.CalculatorService.ICalculators {
        
        public CalculatorsClient() {
        }
        
        public CalculatorsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Add(double numberA, double numberB) {
            return base.Channel.Add(numberA, numberB);
        }
        
        public string Subtract(double numberA, double numberB) {
            return base.Channel.Subtract(numberA, numberB);
        }
        
        public string Multiply(double numberA, double numberB) {
            return base.Channel.Multiply(numberA, numberB);
        }
        
        public string Divide(double numberA, double numberB) {
            return base.Channel.Divide(numberA, numberB);
        }
    }
}
